# Generated by Django 5.2.4 on 2025-07-27 09:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='games/animals/')),
                ('sound', models.FileField(blank=True, null=True, upload_to='games/sounds/')),
                ('category', models.CharField(default='wild', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalMatchingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1 - Easy'), (2, 'Level 2 - Beginner'), (3, 'Level 3 - Intermediate'), (4, 'Level 4 - Advanced'), (5, 'Level 5 - Expert')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField(default=60, help_text='Time limit in seconds')),
                ('points_per_match', models.IntegerField(default=10)),
                ('required_matches', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('level',)},
            },
        ),
        migrations.CreateModel(
            name='AnimalMatchingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_size', models.IntegerField(default=4, help_text='Grid size (e.g., 4 for 4x4 grid)')),
                ('shuffle_count', models.IntegerField(default=3, help_text='Number of times to shuffle cards')),
                ('animals', models.ManyToManyField(related_name='matching_levels', to='games.animal')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='games.animalmatchinggame')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(help_text='Time taken in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalMatchingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_found', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0, help_text='Accuracy percentage')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal_matching', to='games.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level_completed', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'unique_together': {('child', 'game')},
            },
        ),
    ]
