# Generated by Django 5.2.4 on 2025-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Time taken in seconds'),
        ),
    ]
