# Generated by Django 5.2.4 on 2025-07-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamesession_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('category', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorMatchingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField(help_text='Time limit in seconds')),
                ('points_per_match', models.IntegerField(default=10)),
                ('required_matches', models.IntegerField(help_text='Number of matches required to complete level')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.RemoveField(
            model_name='animalmatchinglevel',
            name='animals',
        ),
        migrations.AlterUniqueTogether(
            name='animalmatchinggame',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='animalmatchinglevel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='animalmatchingsession',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='gameprogress',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ColorMatchingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_size', models.IntegerField(default=4, help_text='Grid size (e.g., 4 for 4x4 grid)')),
                ('shuffle_count', models.IntegerField(default=3, help_text='Number of times to shuffle cards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colors', models.ManyToManyField(related_name='levels', to='games.color')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_config', to='games.colormatchinggame')),
            ],
        ),
        migrations.CreateModel(
            name='ColorMatchingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_found', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0, help_text='Accuracy percentage')),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_matching_data', to='games.gamesession')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='AnimalMatchingGame',
        ),
        migrations.DeleteModel(
            name='AnimalMatchingLevel',
        ),
        migrations.DeleteModel(
            name='AnimalMatchingSession',
        ),
    ]
