# Generated by Django 5.2.4 on 2025-07-27 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Drawing', max_length=200)),
                ('canvas_data', models.JSONField(default=dict, help_text='Serialized canvas drawing data')),
                ('canvas_width', models.PositiveIntegerField(default=800)),
                ('canvas_height', models.PositiveIntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('shared_with_parents', models.BooleanField(default=True)),
                ('shared_with_therapists', models.BooleanField(default=True)),
                ('shared_with_teachers', models.BooleanField(default=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('child', models.ForeignKey(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to=settings.AUTH_USER_MODEL)),
                ('parent_drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drawing.drawing')),
            ],
            options={
                'verbose_name': 'drawing',
                'verbose_name_plural': 'drawings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('strokes_count', models.PositiveIntegerField(default=0)),
                ('colors_used', models.JSONField(default=list)),
                ('tools_used', models.JSONField(default=list)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='drawing.drawing')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
