# Generated by Django 5.2.4 on 2025-07-27 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role__in': ['therapist', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(blank=True, null=True)),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='therapy.activityassignment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('matching', 'Matching Game'), ('focus', 'Focus Activity'), ('memory', 'Memory Game'), ('motor', 'Motor Skills'), ('sorting', 'Sorting Activity'), ('sequencing', 'Sequencing Activity')], default='matching', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('instructions', models.TextField(help_text='Instructions for the child')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['therapist', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Therapy activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='activity_audio/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('group_id', models.CharField(blank=True, help_text='For grouping related items together', max_length=50, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='therapy.therapyactivity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='activityassignment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='therapy.therapyactivity'),
        ),
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('matching', 'Matching Game'), ('focus', 'Focus Activity'), ('memory', 'Memory Game'), ('motor', 'Motor Skills'), ('sorting', 'Sorting Activity'), ('sequencing', 'Sequencing Activity')], max_length=20)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('successful_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('child', 'activity_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityassignment',
            unique_together={('activity', 'child')},
        ),
    ]
